version: '3'
services:
  client-mobile:
    build: ./mobile/
    volumes:
      - data-volume:usr/src/app/android/build/outputs/apk/release/
    ports:
       - "8002:8002"
  client-web:
    build: ./client-web/
    volumes:
      - data-volume:/usr/src/assets/
    ports:
       - "8081:8081"
  server:
     container_name: server
     build:
      context: ./Area_api
     ports:
      - "8080:80"
     restart: always
     volumes:
      - data-volume:/var/lib/
     deploy:
      restart_policy:
       condition: any
#  mobile-test:
#    build: ./client_mobile/      #j'ai mis ionic dev copy dans un dossier DEV_MOBILE
#    volumes:
    #   - data-volume:/var/lib/db
    # restart: always
    # deploy:
    #  restart_policy:
    #   condition: any
volumes:
  data-volume:


#         FROM ubuntu:xenial
#
#         LABEL MAINTAINER="Weerayut Hongsa <kusumoto.com@gmail.com>"
#
#         ARG NODEJS_VERSION="10"
#         ARG IONIC_VERSION="4.2.1"
#         ARG ANDROID_SDK_VERSION="3859397"
#         ARG ANDROID_HOME="/opt/android-sdk"
#         ARG ANDROID_BUILD_TOOLS_VERSION="26.0.2"
#
#
#
#         ENV ANDROID_HOME "${ANDROID_HOME}"
#
#         RUN apt-get update \
#         && apt-get install -y \
#         build-essential \
#         openjdk-8-jre \
#         openjdk-8-jdk \
#         curl \
#         unzip \
#         git \
#         gradle \
#         && curl -sL https://deb.nodesource.com/setup_${NODEJS_VERSION}.x | bash - \
#         && apt-get update \
#         && apt-get install -y nodejs \
#         && npm install -g cordova ionic@${IONIC_VERSION} \
#         && cd /tmp \
#         && curl -fSLk https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_VERSION}.zip -o sdk-tools-linux-${ANDROID_SDK_VERSION}.zip \
#         && unzip sdk-tools-linux-${ANDROID_SDK_VERSION}.zip \
#         && mkdir /opt/android-sdk \
#         && mv tools /opt/android-sdk \
#         && (while sleep 3; do echo "y"; done) | $ANDROID_HOME/tools/bin/sdkmanager --licenses \
#         && $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" \
#         && $ANDROID_HOME/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
#         && apt-get autoremove -y \
#         && rm -rf /tmp/sdk-tools-linux-${ANDROID_SDK_VERSION}.zip \
#         && mkdir /ionicapp
#
#         WORKDIR /ionicapp


#version: '3.7'
#services:
#  client-web:
#    build: ./client-web/
#    ports:
#      - "8081:8081"
#    volumes:
#      - type: volume
#        source: data
#        target: /var/lib
#        volume:
#          nocopy: true
#  mobile-test:
#    build: ./DEV_MOBILE/      #j'ai mis ionic dev copy dans un dossier DEV_MOBILE
#    volumes:
#      - type: volume
#        source: data
#        target: /var/lib
#        volume:
#          nocopy: true
#  server:
#    container_name: server
#    build:
#      context: ./Area_api
#    ports:
#      - "8080:80"
#    restart: always
#    deploy:
#      restart_policy:
#        condition: any
#volumes:
 # data: